/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminJframes;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import whatever.proyectocajero.SQLConection;
import whatever.proyectocajero.SharedAdminData;

/**
 *
 * @author ALEJANDRO REQUENA
 */
public class InitATM extends javax.swing.JFrame {

    /**
     * Creates new form InitATM
     */
    public InitATM() {
        initComponents();
        this.setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bgATMupper = new javax.swing.JPanel();
        BackHomeLobby = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bgLowerATM = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Field1Money = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        InitBtn = new javax.swing.JButton();
        FieldMoney5 = new javax.swing.JTextField();
        FieldMoney10 = new javax.swing.JTextField();
        FieldMoney20 = new javax.swing.JTextField();
        FieldMoney50 = new javax.swing.JTextField();
        FieldMoney100 = new javax.swing.JTextField();
        FieldMoney200 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(647, 380));

        jPanel1.setLayout(new java.awt.BorderLayout());

        bgATMupper.setBackground(new java.awt.Color(255, 255, 255));

        BackHomeLobby.setBackground(new java.awt.Color(255, 255, 255));
        BackHomeLobby.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        BackHomeLobby.setForeground(new java.awt.Color(6, 90, 216));
        BackHomeLobby.setText("Regresar");
        BackHomeLobby.setBorder(null);
        BackHomeLobby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackHomeLobbyActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 90, 216));
        jLabel1.setText("Inicializar Cajero");
        jPanel3.add(jLabel1, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout bgATMupperLayout = new javax.swing.GroupLayout(bgATMupper);
        bgATMupper.setLayout(bgATMupperLayout);
        bgATMupperLayout.setHorizontalGroup(
            bgATMupperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgATMupperLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackHomeLobby, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );
        bgATMupperLayout.setVerticalGroup(
            bgATMupperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgATMupperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgATMupperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(BackHomeLobby, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(bgATMupper, java.awt.BorderLayout.PAGE_START);

        bgLowerATM.setBackground(new java.awt.Color(6, 90, 216));

        jPanel2.setBackground(new java.awt.Color(7, 117, 228));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("1.00Q");

        Field1Money.setBackground(new java.awt.Color(255, 255, 255));
        Field1Money.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        Field1Money.setForeground(new java.awt.Color(0, 0, 0));
        Field1Money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field1MoneyActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("5.00Q");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("10.00Q");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("20.00Q");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("200.00Q");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("50.00Q");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("100.00Q");

        InitBtn.setBackground(new java.awt.Color(255, 11, 79));
        InitBtn.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        InitBtn.setForeground(new java.awt.Color(255, 255, 255));
        InitBtn.setText("Inicializar");
        InitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InitBtnActionPerformed(evt);
            }
        });

        FieldMoney5.setBackground(new java.awt.Color(255, 255, 255));
        FieldMoney5.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        FieldMoney5.setForeground(new java.awt.Color(0, 0, 0));
        FieldMoney5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldMoney5ActionPerformed(evt);
            }
        });

        FieldMoney10.setBackground(new java.awt.Color(255, 255, 255));
        FieldMoney10.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        FieldMoney10.setForeground(new java.awt.Color(0, 0, 0));

        FieldMoney20.setBackground(new java.awt.Color(255, 255, 255));
        FieldMoney20.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        FieldMoney20.setForeground(new java.awt.Color(0, 0, 0));
        FieldMoney20.setName(""); // NOI18N
        FieldMoney20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldMoney20ActionPerformed(evt);
            }
        });

        FieldMoney50.setBackground(new java.awt.Color(255, 255, 255));
        FieldMoney50.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        FieldMoney50.setForeground(new java.awt.Color(0, 0, 0));

        FieldMoney100.setBackground(new java.awt.Color(255, 255, 255));
        FieldMoney100.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        FieldMoney100.setForeground(new java.awt.Color(0, 0, 0));
        FieldMoney100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldMoney100ActionPerformed(evt);
            }
        });

        FieldMoney200.setBackground(new java.awt.Color(255, 255, 255));
        FieldMoney200.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        FieldMoney200.setForeground(new java.awt.Color(0, 0, 0));
        FieldMoney200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldMoney200ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FieldMoney20, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(Field1Money)
                    .addComponent(FieldMoney10)
                    .addComponent(FieldMoney5))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FieldMoney50)
                            .addComponent(FieldMoney100)
                            .addComponent(FieldMoney200))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(InitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addGap(77, 77, 77))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Field1Money))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FieldMoney50)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1)))))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FieldMoney5)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FieldMoney100)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(FieldMoney10))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FieldMoney200)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(3, 3, 3)))))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FieldMoney20)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addComponent(InitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout bgLowerATMLayout = new javax.swing.GroupLayout(bgLowerATM);
        bgLowerATM.setLayout(bgLowerATMLayout);
        bgLowerATMLayout.setHorizontalGroup(
            bgLowerATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLowerATMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bgLowerATMLayout.setVerticalGroup(
            bgLowerATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLowerATMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(bgLowerATM, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackHomeLobbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackHomeLobbyActionPerformed
        MainAdminLobby LobbyAdmin = new MainAdminLobby(SharedAdminData.getLoginName(),SharedAdminData.PassUser);
        LobbyAdmin.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_BackHomeLobbyActionPerformed

    private void FieldMoney5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldMoney5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldMoney5ActionPerformed

    private void FieldMoney200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldMoney200ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldMoney200ActionPerformed

    private void FieldMoney100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldMoney100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldMoney100ActionPerformed

    private void FieldMoney20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldMoney20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldMoney20ActionPerformed

    public int GetId(){
        SQLConection sqlConnection = new SQLConection();
        Connection conn = sqlConnection.StartSQLConnection();
        int idCajero = -1;
        String sqlId = "SELECT TOP 1 id_cajero FROM CAJERO ORDER BY id_cajero DESC";
        try(PreparedStatement psmt = conn.prepareStatement(sqlId)){
            ResultSet rs = psmt.executeQuery();
            if(rs.next()){
               return idCajero = rs.getInt("id_cajero");
            }
        } catch(SQLException e){
            return -1;
        }  
        return idCajero;
    }
    private void InitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InitBtnActionPerformed
        SQLConection sqlConnection = new SQLConection();
        Connection conn = sqlConnection.StartSQLConnection();
        int idCajero = GetId();
        try{
            if(isCajeroInitialized(conn,idCajero)){
                JOptionPane.showMessageDialog(this,"EL cajero ya fue inicializado");
                return;
            }
            
            if(Field1Money.getText().isEmpty() || FieldMoney5.getText().isEmpty() || FieldMoney10.getText().isEmpty()
            || FieldMoney20.getText().isEmpty() || FieldMoney50.getText().isEmpty() || FieldMoney100.getText().isEmpty()
            || FieldMoney200.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Tienes que rellenar todos los campos jajaj","freskiala papa",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try {
        int billetes1 = Integer.parseInt(Field1Money.getText());
        int billetes5 = Integer.parseInt(FieldMoney5.getText());
        int billetes10 = Integer.parseInt(FieldMoney10.getText());
        int billetes20 = Integer.parseInt(FieldMoney20.getText());
        int billetes50 = Integer.parseInt(FieldMoney50.getText());
        int billetes100 = Integer.parseInt(FieldMoney100.getText());
        int billetes200 = Integer.parseInt(FieldMoney200.getText());
        
        BigDecimal totalDinero = new BigDecimal(billetes1 * 1 + billetes5 * 5 + billetes10 * 10 +
                                                billetes20 * 20 + billetes50 * 50 + billetes100 * 100 +
                                                billetes200 * 200);
        
        if(totalDinero.compareTo(new BigDecimal(10000)) > 0){
            JOptionPane.showMessageDialog(this, "La cantidad no puede exceder los Q10,000.00");
            return;
        }
        
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Solo se permiten valores numericos en los campos","En donde me dejaste, me pierdo sin ti",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
        int billetes1 = Integer.parseInt(Field1Money.getText());
        int billetes5 = Integer.parseInt(FieldMoney5.getText());
        int billetes10 = Integer.parseInt(FieldMoney10.getText());
        int billetes20 = Integer.parseInt(FieldMoney20.getText());
        int billetes50 = Integer.parseInt(FieldMoney50.getText());
        int billetes100 = Integer.parseInt(FieldMoney100.getText());
        int billetes200 = Integer.parseInt(FieldMoney200.getText());
        
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Solo caracteres numericos","OSCAR OZZIEL OSAIAS YAXCAL LEAL",JOptionPane.WARNING_MESSAGE);
        }
        int billetes1 = Integer.parseInt(Field1Money.getText());
        int billetes5 = Integer.parseInt(FieldMoney5.getText());
        int billetes10 = Integer.parseInt(FieldMoney10.getText());
        int billetes20 = Integer.parseInt(FieldMoney20.getText());
        int billetes50 = Integer.parseInt(FieldMoney50.getText());
        int billetes100 = Integer.parseInt(FieldMoney100.getText());
        int billetes200 = Integer.parseInt(FieldMoney200.getText());
        if(!(billetes1 >= 0 && billetes5 >= 0 && billetes10 >= 0 && billetes20 >= 0 && billetes50 >= 0
             && billetes100 >= 0 && billetes200 >= 0)){
            JOptionPane.showMessageDialog(this, "No creo que existan billetes negativos entonces solo podemos agregar "
                    + "valores positivos");
            return;
        }
        BigDecimal totalDinero = new BigDecimal(billetes1 * 1 + billetes5 * 5 + billetes10 * 10 +
                                                billetes20 * 20 + billetes50 * 50 + billetes100 * 100 +
                                                billetes200 * 200);
        
        String sql = "INSERT INTO CAJERO (total_dinero, billetes_200, billetes_100, billetes_50, billetes_20, billetes_10, billetes_5, billetes_1, estado_inicializado) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1)"; 

        try(PreparedStatement psmt = conn.prepareStatement(sql)){
            psmt.setBigDecimal(1,totalDinero);
            psmt.setInt(2,billetes200);
            psmt.setInt(3, billetes100);
            psmt.setInt(4, billetes50);
            psmt.setInt(5, billetes20);
            psmt.setInt(6, billetes10);
            psmt.setInt(7, billetes5);
            psmt.setInt(8, billetes1);
            
            
            int rowsAffected = psmt.executeUpdate();
            if(rowsAffected > 0){
                JOptionPane.showMessageDialog(this, "Cajero inicializado correctamente");
            } else{
                JOptionPane.showConfirmDialog(this, "Error algo malo salio");
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error al conectar la base de datos");
            }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error al verificar el estado del cajero: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        
        
        
    }//GEN-LAST:event_InitBtnActionPerformed

    private void Field1MoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field1MoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field1MoneyActionPerformed
    private boolean isCajeroInitialized(Connection conn, int idCajero) throws SQLException {
        String query = "SELECT estado_inicializado FROM CAJERO WHERE id_cajero = ?";  
        try (PreparedStatement psmt = conn.prepareStatement(query)) {
            psmt.setInt(1, idCajero);  // Establece el ID del cajero

            try (ResultSet rs = psmt.executeQuery()) {
                if (rs.next()) {
                    // Obtener el valor del campo estado_inicializado
                    boolean estadoInicializado = rs.getBoolean("estado_inicializado");
                    return estadoInicializado;  // Devuelve true si está inicializado (1), false si no (0)
                }
            }
        }
        return false;  // Si no se encuentra el cajero o no hay resultados
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackHomeLobby;
    private javax.swing.JTextField Field1Money;
    private javax.swing.JTextField FieldMoney10;
    private javax.swing.JTextField FieldMoney100;
    private javax.swing.JTextField FieldMoney20;
    private javax.swing.JTextField FieldMoney200;
    private javax.swing.JTextField FieldMoney5;
    private javax.swing.JTextField FieldMoney50;
    private javax.swing.JButton InitBtn;
    private javax.swing.JPanel bgATMupper;
    private javax.swing.JPanel bgLowerATM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
