/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminJframes;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import whatever.proyectocajero.AdminDataSQL;
import whatever.proyectocajero.MenuPrincipal;
import whatever.proyectocajero.SQLConection;
import whatever.proyectocajero.SharedAdminData;

/**
 *
 * @author ALEJANDRO REQUENA
 */
public class LoginAdmin extends javax.swing.JFrame {

    /**
     * Creates new form LoginAdmin
     */
    AdminDataSQL adminDATA = new AdminDataSQL();
    public LoginAdmin() {
        initComponents();
        
                //TAINY REFERENCIA
        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        BgLogin = new javax.swing.JPanel();
        LeftPanelLogin = new javax.swing.JPanel();
        LoginText = new javax.swing.JLabel();
        AdminText = new javax.swing.JLabel();
        TxtFieldAdminKey1 = new javax.swing.JTextField();
        PasswordTextAdmin = new javax.swing.JLabel();
        TxtPasswordFielAdminKey2 = new javax.swing.JPasswordField();
        SignUpBtnAdmin = new javax.swing.JButton();
        HighRighPanelAdmin = new javax.swing.JPanel();
        RighPanelAdmin = new javax.swing.JPanel();
        ComeHomeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(762, 364));

        BgLogin.setLayout(new java.awt.GridLayout(1, 0));

        LeftPanelLogin.setBackground(new java.awt.Color(255, 255, 255));
        LeftPanelLogin.setPreferredSize(new java.awt.Dimension(382, 320));
        LeftPanelLogin.setLayout(new java.awt.GridBagLayout());

        LoginText.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        LoginText.setForeground(new java.awt.Color(6, 90, 216));
        LoginText.setText("Login de administracion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 28, 0, 6);
        LeftPanelLogin.add(LoginText, gridBagConstraints);

        AdminText.setBackground(new java.awt.Color(0, 0, 0));
        AdminText.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        AdminText.setForeground(new java.awt.Color(0, 0, 0));
        AdminText.setText("Admin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 28, 0, 6);
        LeftPanelLogin.add(AdminText, gridBagConstraints);

        TxtFieldAdminKey1.setBackground(new java.awt.Color(255, 255, 255));
        TxtFieldAdminKey1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        TxtFieldAdminKey1.setForeground(new java.awt.Color(0, 0, 0));
        TxtFieldAdminKey1.setCaretColor(new java.awt.Color(0, 0, 0));
        TxtFieldAdminKey1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtFieldAdminKey1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldAdminKey1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 269;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 28, 0, 0);
        LeftPanelLogin.add(TxtFieldAdminKey1, gridBagConstraints);

        PasswordTextAdmin.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        PasswordTextAdmin.setForeground(new java.awt.Color(0, 0, 0));
        PasswordTextAdmin.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 239;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 28, 0, 6);
        LeftPanelLogin.add(PasswordTextAdmin, gridBagConstraints);

        TxtPasswordFielAdminKey2.setBackground(new java.awt.Color(255, 255, 255));
        TxtPasswordFielAdminKey2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        TxtPasswordFielAdminKey2.setForeground(new java.awt.Color(0, 0, 0));
        TxtPasswordFielAdminKey2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPasswordFielAdminKey2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 271;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 28, 0, 0);
        LeftPanelLogin.add(TxtPasswordFielAdminKey2, gridBagConstraints);

        SignUpBtnAdmin.setBackground(new java.awt.Color(6, 90, 216));
        SignUpBtnAdmin.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        SignUpBtnAdmin.setForeground(new java.awt.Color(255, 255, 255));
        SignUpBtnAdmin.setText("Entrar");
        SignUpBtnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBtnAdminActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 249;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 28, 32, 0);
        LeftPanelLogin.add(SignUpBtnAdmin, gridBagConstraints);

        BgLogin.add(LeftPanelLogin);

        HighRighPanelAdmin.setBackground(new java.awt.Color(6, 90, 216));

        RighPanelAdmin.setBackground(new java.awt.Color(7, 117, 228));
        RighPanelAdmin.setLayout(new java.awt.GridBagLayout());

        ComeHomeBtn.setBackground(new java.awt.Color(255, 255, 255));
        ComeHomeBtn.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        ComeHomeBtn.setForeground(new java.awt.Color(51, 51, 255));
        ComeHomeBtn.setText("Regresar");
        ComeHomeBtn.setBorder(null);
        ComeHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComeHomeBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(94, 62, 91, 61);
        RighPanelAdmin.add(ComeHomeBtn, gridBagConstraints);

        javax.swing.GroupLayout HighRighPanelAdminLayout = new javax.swing.GroupLayout(HighRighPanelAdmin);
        HighRighPanelAdmin.setLayout(HighRighPanelAdminLayout);
        HighRighPanelAdminLayout.setHorizontalGroup(
            HighRighPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HighRighPanelAdminLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(RighPanelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );
        HighRighPanelAdminLayout.setVerticalGroup(
            HighRighPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HighRighPanelAdminLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(RighPanelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56))
        );

        BgLogin.add(HighRighPanelAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtPasswordFielAdminKey2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPasswordFielAdminKey2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPasswordFielAdminKey2ActionPerformed

    private void TxtFieldAdminKey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldAdminKey1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldAdminKey1ActionPerformed

    private void SignUpBtnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBtnAdminActionPerformed
        
        
    /* Unicamente para ver si esta conectada la base de datos    if (conn == null) {
        JOptionPane.showMessageDialog(this, "No database connection.");
        return;
        }
        else{
            JOptionPane.showConfirmDialog(this, "Succesful connection");
        }
        */
        if(TxtPasswordFielAdminKey2.getText().isEmpty() || TxtFieldAdminKey1.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this,"Todos los campos deben ser llenados!","Llena esas mierdas vos",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String userGet = TxtFieldAdminKey1.getText();
        String passGet = TxtPasswordFielAdminKey2.getText();

        Boolean flag = adminDATA.CheckLoginAdminData(userGet, passGet);
        if(flag == true){
            JOptionPane.showMessageDialog(this, "Entrada satisfactoria, bienvenido otra vez! " + SharedAdminData.getLoginName());   
                MainAdminLobby mainlobbyWindow = new MainAdminLobby(SharedAdminData.getLoginName(),SharedAdminData.getPassword());             
                mainlobbyWindow.setVisible(true);
                this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this,"No es valido: Contraseña o usuario incorrectos","Si hoy me odias, yo no te culpo pero te necesito",JOptionPane.INFORMATION_MESSAGE);
        }      
    }//GEN-LAST:event_SignUpBtnAdminActionPerformed

    private void ComeHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComeHomeBtnActionPerformed
        MenuPrincipal MenuMain = new MenuPrincipal();
        MenuMain.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_ComeHomeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminText;
    private javax.swing.JPanel BgLogin;
    private javax.swing.JButton ComeHomeBtn;
    private javax.swing.JPanel HighRighPanelAdmin;
    private javax.swing.JPanel LeftPanelLogin;
    private javax.swing.JLabel LoginText;
    private javax.swing.JLabel PasswordTextAdmin;
    private javax.swing.JPanel RighPanelAdmin;
    private javax.swing.JButton SignUpBtnAdmin;
    private javax.swing.JTextField TxtFieldAdminKey1;
    private javax.swing.JPasswordField TxtPasswordFielAdminKey2;
    // End of variables declaration//GEN-END:variables
}
