/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminJframes;

import AdminJframes.InitATM;
import AdminJframes.LoginAdmin;
import AdminJframes.AddMoney;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import whatever.proyectocajero.SharedAdminData;


public class MainAdminLobby extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainAdminLobby() {
        initComponents();
        this.setLocationRelativeTo(null);
        System.out.println("Constructor without parameters called.");  

        
    }
    public MainAdminLobby(String user,String pass) {
        initComponents();
        this.setLocationRelativeTo(null);
        NameAdminLabel.setText(user);
        System.out.println("Constructor with parameter called. User: " + user);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LeftEdgeLobbyAdmin = new javax.swing.JPanel();
        BackToMenuBtn = new javax.swing.JButton();
        ConsultUser = new javax.swing.JButton();
        BgRightLobbyAdmin = new javax.swing.JPanel();
        UpperEdgeLobbyAdmin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NameAdminLabel = new javax.swing.JLabel();
        BgCenterLobbyAdmin = new javax.swing.JPanel();
        CreateUsersBtn = new javax.swing.JButton();
        AddMoneyBtn = new javax.swing.JButton();
        ModMaxAmountBtn = new javax.swing.JButton();
        InitATSbtn = new javax.swing.JButton();
        ModUserNumberTargetBtn = new javax.swing.JButton();
        UsersControlBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(647, 380));

        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        LeftEdgeLobbyAdmin.setBackground(new java.awt.Color(255, 255, 255));
        LeftEdgeLobbyAdmin.setPreferredSize(new java.awt.Dimension(180, 490));

        BackToMenuBtn.setBackground(new java.awt.Color(255, 255, 255));
        BackToMenuBtn.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        BackToMenuBtn.setForeground(new java.awt.Color(0, 0, 0));
        BackToMenuBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEJANDRO REQUENA\\Documents\\NetBeansProjects\\ProyectoCajero\\src\\main\\java\\imagees\\back-to-home.png")); // NOI18N
        BackToMenuBtn.setText("Salir al inicio");
        BackToMenuBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        BackToMenuBtn.setBorderPainted(false);
        BackToMenuBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BackToMenuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackToMenuBtnMouseEntered(evt);
            }
        });
        BackToMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuBtnActionPerformed(evt);
            }
        });

        ConsultUser.setBackground(new java.awt.Color(255, 255, 255));
        ConsultUser.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        ConsultUser.setForeground(new java.awt.Color(0, 0, 0));
        ConsultUser.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEJANDRO REQUENA\\Documents\\NetBeansProjects\\ProyectoCajero\\src\\main\\java\\imagees\\magnifying-glass.png")); // NOI18N
        ConsultUser.setText("Consultar");
        ConsultUser.setBorder(null);
        ConsultUser.setBorderPainted(false);
        ConsultUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ConsultUser.setFocusPainted(false);
        ConsultUser.setFocusable(false);
        ConsultUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftEdgeLobbyAdminLayout = new javax.swing.GroupLayout(LeftEdgeLobbyAdmin);
        LeftEdgeLobbyAdmin.setLayout(LeftEdgeLobbyAdminLayout);
        LeftEdgeLobbyAdminLayout.setHorizontalGroup(
            LeftEdgeLobbyAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackToMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(ConsultUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LeftEdgeLobbyAdminLayout.setVerticalGroup(
            LeftEdgeLobbyAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftEdgeLobbyAdminLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(BackToMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(ConsultUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(174, 174, 174))
        );

        jPanel2.add(LeftEdgeLobbyAdmin, java.awt.BorderLayout.LINE_START);

        BgRightLobbyAdmin.setBackground(new java.awt.Color(241, 241, 241));

        UpperEdgeLobbyAdmin.setBackground(new java.awt.Color(20, 51, 125));
        UpperEdgeLobbyAdmin.setPreferredSize(new java.awt.Dimension(740, 90));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bienvenido admin");

        NameAdminLabel.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        NameAdminLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameAdminLabel.setText("Example");

        javax.swing.GroupLayout UpperEdgeLobbyAdminLayout = new javax.swing.GroupLayout(UpperEdgeLobbyAdmin);
        UpperEdgeLobbyAdmin.setLayout(UpperEdgeLobbyAdminLayout);
        UpperEdgeLobbyAdminLayout.setHorizontalGroup(
            UpperEdgeLobbyAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperEdgeLobbyAdminLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NameAdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UpperEdgeLobbyAdminLayout.setVerticalGroup(
            UpperEdgeLobbyAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperEdgeLobbyAdminLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(UpperEdgeLobbyAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NameAdminLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        BgCenterLobbyAdmin.setBackground(new java.awt.Color(228, 228, 228));

        CreateUsersBtn.setBackground(new java.awt.Color(255, 255, 255));
        CreateUsersBtn.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        CreateUsersBtn.setForeground(new java.awt.Color(0, 0, 0));
        CreateUsersBtn.setText("Creación de usuarios");
        CreateUsersBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CreateUsersBtn.setBorderPainted(false);
        CreateUsersBtn.setFocusable(false);
        CreateUsersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateUsersBtnActionPerformed(evt);
            }
        });

        AddMoneyBtn.setBackground(new java.awt.Color(255, 255, 255));
        AddMoneyBtn.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        AddMoneyBtn.setForeground(new java.awt.Color(0, 0, 0));
        AddMoneyBtn.setText("Agregar efectivo");
        AddMoneyBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AddMoneyBtn.setBorderPainted(false);
        AddMoneyBtn.setFocusable(false);
        AddMoneyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMoneyBtnActionPerformed(evt);
            }
        });

        ModMaxAmountBtn.setBackground(new java.awt.Color(255, 255, 255));
        ModMaxAmountBtn.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        ModMaxAmountBtn.setForeground(new java.awt.Color(0, 0, 0));
        ModMaxAmountBtn.setText("Modificar Limite");
        ModMaxAmountBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ModMaxAmountBtn.setBorderPainted(false);
        ModMaxAmountBtn.setFocusable(false);
        ModMaxAmountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModMaxAmountBtnActionPerformed(evt);
            }
        });

        InitATSbtn.setBackground(new java.awt.Color(255, 255, 255));
        InitATSbtn.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        InitATSbtn.setForeground(new java.awt.Color(0, 0, 0));
        InitATSbtn.setText("Inicializar cajero");
        InitATSbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        InitATSbtn.setBorderPainted(false);
        InitATSbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InitATSbtnMouseEntered(evt);
            }
        });
        InitATSbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InitATSbtnActionPerformed(evt);
            }
        });

        ModUserNumberTargetBtn.setBackground(new java.awt.Color(255, 255, 255));
        ModUserNumberTargetBtn.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        ModUserNumberTargetBtn.setForeground(new java.awt.Color(0, 0, 0));
        ModUserNumberTargetBtn.setText("Modificar Tarjeta");
        ModUserNumberTargetBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ModUserNumberTargetBtn.setBorderPainted(false);
        ModUserNumberTargetBtn.setFocusable(false);
        ModUserNumberTargetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModUserNumberTargetBtnActionPerformed(evt);
            }
        });

        UsersControlBtn.setBackground(new java.awt.Color(255, 255, 255));
        UsersControlBtn.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        UsersControlBtn.setForeground(new java.awt.Color(0, 0, 0));
        UsersControlBtn.setText("Control De Usuarios");
        UsersControlBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UsersControlBtn.setBorderPainted(false);
        UsersControlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersControlBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BgCenterLobbyAdminLayout = new javax.swing.GroupLayout(BgCenterLobbyAdmin);
        BgCenterLobbyAdmin.setLayout(BgCenterLobbyAdminLayout);
        BgCenterLobbyAdminLayout.setHorizontalGroup(
            BgCenterLobbyAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BgCenterLobbyAdminLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(BgCenterLobbyAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BgCenterLobbyAdminLayout.createSequentialGroup()
                        .addComponent(ModMaxAmountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(ModUserNumberTargetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UsersControlBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                    .addComponent(InitATSbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BgCenterLobbyAdminLayout.createSequentialGroup()
                        .addComponent(CreateUsersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(AddMoneyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
        );
        BgCenterLobbyAdminLayout.setVerticalGroup(
            BgCenterLobbyAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BgCenterLobbyAdminLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(InitATSbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BgCenterLobbyAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModMaxAmountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(ModUserNumberTargetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UsersControlBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(BgCenterLobbyAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddMoneyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(CreateUsersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout BgRightLobbyAdminLayout = new javax.swing.GroupLayout(BgRightLobbyAdmin);
        BgRightLobbyAdmin.setLayout(BgRightLobbyAdminLayout);
        BgRightLobbyAdminLayout.setHorizontalGroup(
            BgRightLobbyAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpperEdgeLobbyAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BgCenterLobbyAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BgRightLobbyAdminLayout.setVerticalGroup(
            BgRightLobbyAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgRightLobbyAdminLayout.createSequentialGroup()
                .addComponent(UpperEdgeLobbyAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BgCenterLobbyAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(BgRightLobbyAdmin, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuBtnActionPerformed
        LoginAdmin menuLoginAdm = new LoginAdmin();
        menuLoginAdm.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_BackToMenuBtnActionPerformed

    private void CreateUsersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateUsersBtnActionPerformed
        
        TokenOptionCreationUser tokenoptionWindow = new TokenOptionCreationUser();
        tokenoptionWindow.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_CreateUsersBtnActionPerformed

    private void AddMoneyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMoneyBtnActionPerformed
       AddMoney addMoneyPanel = new AddMoney();
       addMoneyPanel.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_AddMoneyBtnActionPerformed

    private void InitATSbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InitATSbtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_InitATSbtnMouseEntered

    private void InitATSbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InitATSbtnActionPerformed
        
        InitATM InitATM = new InitATM();
        InitATM.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_InitATSbtnActionPerformed

    private void BackToMenuBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackToMenuBtnMouseEntered
        
    }//GEN-LAST:event_BackToMenuBtnMouseEntered

    private void ModMaxAmountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModMaxAmountBtnActionPerformed
        ModLimit modLimit = new ModLimit();
        modLimit.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_ModMaxAmountBtnActionPerformed

    private void ModUserNumberTargetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModUserNumberTargetBtnActionPerformed
       ModTarget modTarget = new ModTarget();
       modTarget.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_ModUserNumberTargetBtnActionPerformed

    private void UsersControlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersControlBtnActionPerformed
        UserControl usercontrol = new UserControl();
        usercontrol.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_UsersControlBtnActionPerformed

    private void ConsultUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultUserActionPerformed
        UserQuery userConsult = new UserQuery();
        userConsult.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_ConsultUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdminLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdminLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdminLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdminLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdminLobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMoneyBtn;
    private javax.swing.JButton BackToMenuBtn;
    private javax.swing.JPanel BgCenterLobbyAdmin;
    private javax.swing.JPanel BgRightLobbyAdmin;
    private javax.swing.JButton ConsultUser;
    private javax.swing.JButton CreateUsersBtn;
    private javax.swing.JButton InitATSbtn;
    private javax.swing.JPanel LeftEdgeLobbyAdmin;
    private javax.swing.JButton ModMaxAmountBtn;
    private javax.swing.JButton ModUserNumberTargetBtn;
    private javax.swing.JLabel NameAdminLabel;
    private javax.swing.JPanel UpperEdgeLobbyAdmin;
    private javax.swing.JButton UsersControlBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
