/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminJframes;

import AdminJframes.MainAdminLobby;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import whatever.proyectocajero.SQLConection;
import whatever.proyectocajero.SharedAdminData;

/**
 *
 * @author ALEJANDRO REQUENA
 */
public class ModLimit extends javax.swing.JFrame {

    /**
     * Creates new form ModLimit
     */
    public ModLimit() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ComeBackBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TarjetChangeLimitField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NewTarjetChangeLimitField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ChangeLimitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(714, 549));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ComeBackBtn.setBackground(new java.awt.Color(255, 255, 255));
        ComeBackBtn.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        ComeBackBtn.setForeground(new java.awt.Color(51, 51, 255));
        ComeBackBtn.setText("Regresar");
        ComeBackBtn.setBorder(null);
        ComeBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComeBackBtnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 90, 216));
        jLabel1.setText("Modificar Limite");
        jPanel3.add(jLabel1, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComeBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComeBackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(6, 90, 216));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("No. Tarjeta");

        TarjetChangeLimitField.setBackground(new java.awt.Color(255, 255, 255));
        TarjetChangeLimitField.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        TarjetChangeLimitField.setForeground(new java.awt.Color(0, 0, 0));
        TarjetChangeLimitField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarjetChangeLimitFieldActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Del usuario el cual queremos cambiar el limite");

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nuevo monto");

        NewTarjetChangeLimitField.setBackground(new java.awt.Color(255, 255, 255));
        NewTarjetChangeLimitField.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        NewTarjetChangeLimitField.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nuevo monto maximo que asignaremos al usuario");

        ChangeLimitBtn.setBackground(new java.awt.Color(255, 11, 79));
        ChangeLimitBtn.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        ChangeLimitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ChangeLimitBtn.setText("Cambiar");
        ChangeLimitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeLimitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TarjetChangeLimitField)
                            .addComponent(NewTarjetChangeLimitField)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 566, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ChangeLimitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(47, 47, 47))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TarjetChangeLimitField))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewTarjetChangeLimitField))
                .addGap(76, 76, 76)
                .addComponent(ChangeLimitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComeBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComeBackBtnActionPerformed
       MainAdminLobby LobbyAdmin = new MainAdminLobby(SharedAdminData.getLoginName(),SharedAdminData.getPassword());
        LobbyAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ComeBackBtnActionPerformed

    private void ChangeLimitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeLimitBtnActionPerformed
    SQLConection sqlConnection = new SQLConection();
    Connection conn = sqlConnection.StartSQLConnection();
        
    if(TarjetChangeLimitField.getText().isEmpty() || NewTarjetChangeLimitField.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Rellename todo jajajj");
        return;
    }
    try {
        BigDecimal cardNumber = new BigDecimal(TarjetChangeLimitField.getText());
        BigDecimal newLimit = new BigDecimal(NewTarjetChangeLimitField.getText());
        if(cardNumber.compareTo(BigDecimal.ZERO) < 0 || newLimit.compareTo(BigDecimal.ZERO) < 0){
            JOptionPane.showMessageDialog(this, "Solo valores positivos");
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor ingrese unicamente valores numéricos", "Error en el límite", JOptionPane.WARNING_MESSAGE);
        return;
        }
    
        if(TarjetChangeLimitField.getText().length() != 16 ){
            JOptionPane.showMessageDialog(this, "Las tarjetas solo pueden tener valores de 16 caracteres");
            return;
        }
        
        String numberCard = TarjetChangeLimitField.getText();
        BigDecimal newLimit = new BigDecimal(NewTarjetChangeLimitField.getText());
        
        String checkSQL = "SELECT id_usuario,monto_maximo FROM CREAR_USUARIOS WHERE numero_tarjeta = ?";
        try(PreparedStatement checkCard = conn.prepareStatement(checkSQL)){
            checkCard.setString(1, numberCard);
            ResultSet rs = checkCard.executeQuery();
            if(!rs.next()){
                JOptionPane.showMessageDialog(this, "El usuario con el numero de tarjeta no fue encontrado");
                return;
            }
            
            int numberId = rs.getInt("id_usuario");
            BigDecimal montoMaximoAnterior = rs.getBigDecimal("monto_maximo");
            
            
            String sqlUpdate = "UPDATE CREAR_USUARIOS SET monto_maximo = ?,ultima_modificacion = GETDATE() WHERE numero_tarjeta = ?";
            try(PreparedStatement updateStmt = conn.prepareStatement(sqlUpdate)){
                updateStmt.setBigDecimal(1, newLimit);
                updateStmt.setString(2, numberCard);
                int rowsAffected = updateStmt.executeUpdate();
                
                if(rowsAffected > 0){
                    String InsertSQL = "INSERT INTO MODIFICAR_LIMITE (id_usuario,monto_anterior,monto_nuevo,fecha_modificacion) VALUES (?,?,?,GETDATE())";
                    try(PreparedStatement insertStmt = conn.prepareStatement(InsertSQL)){
                        insertStmt.setInt(1, numberId);
                        insertStmt.setBigDecimal(2, montoMaximoAnterior);
                        insertStmt.setBigDecimal(3, newLimit);
                        insertStmt.executeUpdate();
                        
                        JOptionPane.showMessageDialog(this, "EL NUMERO DE LA TARJETA HA SIDO AGREGADO CON EXITO EPICO","FELIZ CUMPLE DIDIER CALEL SIS",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                else{
                    JOptionPane.showConfirmDialog(this, "Error al modificar la tarjeta");
                    conn.rollback();
                }
            }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error de SQL: " + e.getMessage(),"Civil Calel Sis Didier Marco Josué",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_ChangeLimitBtnActionPerformed

    private void TarjetChangeLimitFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarjetChangeLimitFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TarjetChangeLimitFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModLimit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModLimit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModLimit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModLimit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModLimit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeLimitBtn;
    private javax.swing.JButton ComeBackBtn;
    private javax.swing.JTextField NewTarjetChangeLimitField;
    private javax.swing.JTextField TarjetChangeLimitField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
