/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminJframes;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import whatever.proyectocajero.SQLConection;
import whatever.proyectocajero.SharedAdminData;

/**
 *
 * @author ALEJANDRO REQUENA
 */
public class UserCreationPlusToken extends javax.swing.JFrame {

    /**
     * Creates new form UserCreationPlusToken
     */
    public UserCreationPlusToken() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        Upperbg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BackLobby = new javax.swing.JButton();
        CenterBg = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NameFieldCreateUser = new javax.swing.JTextField();
        PINfieldUser = new javax.swing.JTextField();
        UserNumberTargetField = new javax.swing.JTextField();
        BalanceUserField = new javax.swing.JTextField();
        MaxAmountUserFIeld = new javax.swing.JTextField();
        EnterDataBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TokenFieldUser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        Upperbg.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(6, 90, 216));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 90, 216));
        jLabel1.setText("Creacion de usuarios");
        jLabel1.setAutoscrolls(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 6, 27, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        BackLobby.setBackground(new java.awt.Color(255, 255, 255));
        BackLobby.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        BackLobby.setForeground(new java.awt.Color(51, 51, 255));
        BackLobby.setText("Regresar");
        BackLobby.setBorder(null);
        BackLobby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackLobbyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpperbgLayout = new javax.swing.GroupLayout(Upperbg);
        Upperbg.setLayout(UpperbgLayout);
        UpperbgLayout.setHorizontalGroup(
            UpperbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperbgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackLobby, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );
        UpperbgLayout.setVerticalGroup(
            UpperbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperbgLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(UpperbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(BackLobby, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(Upperbg, java.awt.BorderLayout.PAGE_START);

        CenterBg.setBackground(new java.awt.Color(6, 90, 216));
        CenterBg.setForeground(new java.awt.Color(218, 218, 218));

        jPanel3.setBackground(new java.awt.Color(7, 117, 228));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 113, 0, 0);
        jPanel3.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No. de tarjeta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 46, 0, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 170, 0, 0);
        jPanel3.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Saldo Actual");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 58, 0, 0);
        jPanel3.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Monto maximo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 24, 0, 0);
        jPanel3.add(jLabel6, gridBagConstraints);

        NameFieldCreateUser.setBackground(new java.awt.Color(255, 255, 255));
        NameFieldCreateUser.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        NameFieldCreateUser.setForeground(new java.awt.Color(0, 0, 0));
        NameFieldCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldCreateUserActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 518;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 18, 0, 23);
        jPanel3.add(NameFieldCreateUser, gridBagConstraints);

        PINfieldUser.setBackground(new java.awt.Color(255, 255, 255));
        PINfieldUser.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        PINfieldUser.setForeground(new java.awt.Color(0, 0, 0));
        PINfieldUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PINfieldUserKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 518;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 23);
        jPanel3.add(PINfieldUser, gridBagConstraints);

        UserNumberTargetField.setBackground(new java.awt.Color(255, 255, 255));
        UserNumberTargetField.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        UserNumberTargetField.setForeground(new java.awt.Color(0, 0, 0));
        UserNumberTargetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNumberTargetFieldActionPerformed(evt);
            }
        });
        UserNumberTargetField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UserNumberTargetFieldKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 518;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 18, 0, 23);
        jPanel3.add(UserNumberTargetField, gridBagConstraints);

        BalanceUserField.setBackground(new java.awt.Color(255, 255, 255));
        BalanceUserField.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        BalanceUserField.setForeground(new java.awt.Color(0, 0, 0));
        BalanceUserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceUserFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 518;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 18, 0, 23);
        jPanel3.add(BalanceUserField, gridBagConstraints);

        MaxAmountUserFIeld.setBackground(new java.awt.Color(255, 255, 255));
        MaxAmountUserFIeld.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        MaxAmountUserFIeld.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 518;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 18, 0, 23);
        jPanel3.add(MaxAmountUserFIeld, gridBagConstraints);

        EnterDataBtn.setBackground(new java.awt.Color(255, 11, 79));
        EnterDataBtn.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        EnterDataBtn.setForeground(new java.awt.Color(255, 255, 255));
        EnterDataBtn.setText("Crear Usuario");
        EnterDataBtn.setBorder(null);
        EnterDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterDataBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.ipady = 65;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 114, 17, 0);
        jPanel3.add(EnterDataBtn, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Token");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 136, 0, 0);
        jPanel3.add(jLabel7, gridBagConstraints);

        TokenFieldUser.setBackground(new java.awt.Color(255, 255, 255));
        TokenFieldUser.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        TokenFieldUser.setForeground(new java.awt.Color(0, 0, 0));
        TokenFieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TokenFieldUserActionPerformed(evt);
            }
        });
        TokenFieldUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TokenFieldUserKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 518;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 23);
        jPanel3.add(TokenFieldUser, gridBagConstraints);

        javax.swing.GroupLayout CenterBgLayout = new javax.swing.GroupLayout(CenterBg);
        CenterBg.setLayout(CenterBgLayout);
        CenterBgLayout.setHorizontalGroup(
            CenterBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterBgLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );
        CenterBgLayout.setVerticalGroup(
            CenterBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CenterBgLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jPanel1.add(CenterBg, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackLobbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackLobbyActionPerformed
        MainAdminLobby LobbyAdmin = new MainAdminLobby(SharedAdminData.getLoginName(),SharedAdminData.getPassword());
        LobbyAdmin.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_BackLobbyActionPerformed

    private void UserNumberTargetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNumberTargetFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNumberTargetFieldActionPerformed

    private void EnterDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterDataBtnActionPerformed
        SQLConection sqlConnection = new SQLConection();
        Connection conn = sqlConnection.StartSQLConnection();
        
        if(NameFieldCreateUser.getText().isEmpty() || UserNumberTargetField.getText().isEmpty() || PINfieldUser.getText().isEmpty()
            || BalanceUserField.getText().isEmpty() || MaxAmountUserFIeld.getText().isEmpty() || TokenFieldUser.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Tienes que rellenar todos los campos jajaj","Karen jom no te enseño esta",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        BigDecimal balance; 
        BigDecimal maxAmount;
        try{
            balance = new BigDecimal(BalanceUserField.getText());
            maxAmount = new BigDecimal(MaxAmountUserFIeld.getText());
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "No se pueden agregar caracteres ni cadenas de texto al saldo ni al monto maximo"
                    + " unicamente caracteres numericos.","te encargo porfa",JOptionPane.WARNING_MESSAGE);
            return;
        }       
        
        String name = NameFieldCreateUser.getText();
        String targetNumber = UserNumberTargetField.getText();
        String PIN = PINfieldUser.getText();
        String token = TokenFieldUser.getText();
        
        if(targetNumber.length() != 16){
            JOptionPane.showMessageDialog(this, "Recordate que los numeros de tarjeta solo puede tener 16 caracteres.","hola",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(PIN.length() != 4){
            JOptionPane.showMessageDialog(this, "Recordate que los numeros del PIN solo puede tener 4 caracteres.","sexo",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(token.length() != 6){
            JOptionPane.showMessageDialog(this, "El token solo puede tener exactamente 6 caracteres","Hoy sera mejor que no baje,",JOptionPane.WARNING_MESSAGE);
        }
        
        String sql = "INSERT INTO CREAR_USUARIOS (nombre, numero_tarjeta,PIN,saldo,monto_maximo,token,TokenTipo) VALUES (?,?,?,?,?,?,1)";
        try(PreparedStatement psmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)){
            psmt.setString(1, name);
            psmt.setString(2, targetNumber);
            psmt.setString(3, PIN);
            psmt.setBigDecimal(4, balance);
            psmt.setBigDecimal(5, maxAmount);
            psmt.setString(6, token);
            
            int rowsAffected = psmt.executeUpdate();
            
            if(rowsAffected > 0){
                ResultSet generatedKeys = psmt.getGeneratedKeys();
                
                if (generatedKeys.next()) {
                int idUsuario = generatedKeys.getInt(1);
                
                String sqlInsert = "INSERT INTO CONSULTA_USUARIO (id_usuario, monto_maximo, monto_retirado_hasta_ahora, saldo_actual, ultimo_acceso) VALUES (?, ?, 0, ?, NULL);";
                BigDecimal MaxRestAmoun = maxAmount;
                if(maxAmount.compareTo(balance) > 0){
                    MaxRestAmoun = balance;
                }
                else if(maxAmount.compareTo(balance) < 0){
                    MaxRestAmoun = maxAmount;
                }
                try (PreparedStatement pstmt = conn.prepareStatement(sqlInsert)) {
                pstmt.setInt(1, idUsuario);           
                pstmt.setBigDecimal(2, MaxRestAmoun);   
                pstmt.setBigDecimal(3, balance);     

                int rowsAffectedConsulta = pstmt.executeUpdate();  
                if (rowsAffectedConsulta > 0) {
                    JOptionPane.showMessageDialog(this, "Usuario agregado correctamente");
                } else {
                    JOptionPane.showMessageDialog(this, "Error al registrar la consulta");
                    return;
                        }           
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Error al agregar el usuario");
                return;
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error al conectar la base de datos" + e.getMessage(),"jajaj",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_EnterDataBtnActionPerformed

    private void BalanceUserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceUserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BalanceUserFieldActionPerformed

    private void NameFieldCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldCreateUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldCreateUserActionPerformed

    private void TokenFieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TokenFieldUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TokenFieldUserActionPerformed

    private void TokenFieldUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TokenFieldUserKeyTyped
       
    }//GEN-LAST:event_TokenFieldUserKeyTyped

    private void UserNumberTargetFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserNumberTargetFieldKeyTyped
         char c = evt.getKeyChar();
       if(!Character.isDigit(c)){
           evt.consume();
       }
    }//GEN-LAST:event_UserNumberTargetFieldKeyTyped

    private void PINfieldUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PINfieldUserKeyTyped
         char c = evt.getKeyChar();
       if(!Character.isDigit(c)){
           evt.consume();
       }
    }//GEN-LAST:event_PINfieldUserKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserCreationPlusToken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserCreationPlusToken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserCreationPlusToken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserCreationPlusToken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserCreationPlusToken().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackLobby;
    private javax.swing.JTextField BalanceUserField;
    private javax.swing.JPanel CenterBg;
    private javax.swing.JButton EnterDataBtn;
    private javax.swing.JTextField MaxAmountUserFIeld;
    private javax.swing.JTextField NameFieldCreateUser;
    private javax.swing.JTextField PINfieldUser;
    private javax.swing.JTextField TokenFieldUser;
    private javax.swing.JPanel Upperbg;
    private javax.swing.JTextField UserNumberTargetField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
