/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminJframes;

import AdminJframes.MainAdminLobby;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.security.SecureRandom;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import whatever.proyectocajero.SQLConection;
import whatever.proyectocajero.SharedAdminData;

/**
 *
 * @author ALEJANDRO REQUENA
 */

public class UserCreation extends javax.swing.JFrame {

    /**
     * Creates new form UserCreation
     */

    public UserCreation() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        Upperbg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BackLobby = new javax.swing.JButton();
        CenterBg = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NameFieldCreateUser = new javax.swing.JTextField();
        PINfieldUser = new javax.swing.JTextField();
        UserNumberTargetField = new javax.swing.JTextField();
        BalanceUserField = new javax.swing.JTextField();
        MaxAmountUserFIeld = new javax.swing.JTextField();
        EnterDataBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(714, 549));

        jPanel1.setLayout(new java.awt.BorderLayout());

        Upperbg.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(6, 90, 216));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 90, 216));
        jLabel1.setText("Creacion de usuarios");
        jLabel1.setAutoscrolls(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 6, 27, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        BackLobby.setBackground(new java.awt.Color(255, 255, 255));
        BackLobby.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        BackLobby.setForeground(new java.awt.Color(51, 51, 255));
        BackLobby.setText("Regresar");
        BackLobby.setBorder(null);
        BackLobby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackLobbyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpperbgLayout = new javax.swing.GroupLayout(Upperbg);
        Upperbg.setLayout(UpperbgLayout);
        UpperbgLayout.setHorizontalGroup(
            UpperbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperbgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackLobby, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );
        UpperbgLayout.setVerticalGroup(
            UpperbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperbgLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(UpperbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(BackLobby, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(Upperbg, java.awt.BorderLayout.PAGE_START);

        CenterBg.setBackground(new java.awt.Color(6, 90, 216));
        CenterBg.setForeground(new java.awt.Color(218, 218, 218));

        jPanel3.setBackground(new java.awt.Color(7, 117, 228));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No. de tarjeta");

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PIN");

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Saldo Actual");

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Monto maximo");

        NameFieldCreateUser.setBackground(new java.awt.Color(255, 255, 255));
        NameFieldCreateUser.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        NameFieldCreateUser.setForeground(new java.awt.Color(0, 0, 0));

        PINfieldUser.setBackground(new java.awt.Color(255, 255, 255));
        PINfieldUser.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        PINfieldUser.setForeground(new java.awt.Color(0, 0, 0));
        PINfieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PINfieldUserActionPerformed(evt);
            }
        });
        PINfieldUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PINfieldUserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PINfieldUserKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PINfieldUserKeyTyped(evt);
            }
        });

        UserNumberTargetField.setBackground(new java.awt.Color(255, 255, 255));
        UserNumberTargetField.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        UserNumberTargetField.setForeground(new java.awt.Color(0, 0, 0));
        UserNumberTargetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNumberTargetFieldActionPerformed(evt);
            }
        });
        UserNumberTargetField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UserNumberTargetFieldKeyTyped(evt);
            }
        });

        BalanceUserField.setBackground(new java.awt.Color(255, 255, 255));
        BalanceUserField.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        BalanceUserField.setForeground(new java.awt.Color(0, 0, 0));
        BalanceUserField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BalanceUserFieldKeyTyped(evt);
            }
        });

        MaxAmountUserFIeld.setBackground(new java.awt.Color(255, 255, 255));
        MaxAmountUserFIeld.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        MaxAmountUserFIeld.setForeground(new java.awt.Color(0, 0, 0));
        MaxAmountUserFIeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaxAmountUserFIeldActionPerformed(evt);
            }
        });

        EnterDataBtn.setBackground(new java.awt.Color(255, 11, 79));
        EnterDataBtn.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        EnterDataBtn.setForeground(new java.awt.Color(255, 255, 255));
        EnterDataBtn.setText("Crear Usuario");
        EnterDataBtn.setBorder(null);
        EnterDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterDataBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(NameFieldCreateUser))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(UserNumberTargetField))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(PINfieldUser))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(BalanceUserField))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12)
                        .addComponent(MaxAmountUserFIeld)))
                .addGap(23, 23, 23))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(EnterDataBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGap(258, 258, 258))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(NameFieldCreateUser)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(UserNumberTargetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(PINfieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(BalanceUserField)
                        .addGap(3, 3, 3)))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(MaxAmountUserFIeld)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EnterDataBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout CenterBgLayout = new javax.swing.GroupLayout(CenterBg);
        CenterBg.setLayout(CenterBgLayout);
        CenterBgLayout.setHorizontalGroup(
            CenterBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterBgLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );
        CenterBgLayout.setVerticalGroup(
            CenterBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterBgLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        jPanel1.add(CenterBg, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNumberTargetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNumberTargetFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNumberTargetFieldActionPerformed
    
    private void BackLobbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackLobbyActionPerformed
        MainAdminLobby LobbyAdmin = new MainAdminLobby(SharedAdminData.getLoginName(),SharedAdminData.getPassword());
        LobbyAdmin.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_BackLobbyActionPerformed
    private String generateUniqueToken() { //method random
    Random random = new SecureRandom();
    final String CHARACTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    int tokenLength = 6;
    StringBuilder token = new StringBuilder(tokenLength);
    for (int i = 0; i < tokenLength; i++) {
        int randomindex = random.nextInt(CHARACTERS.length());
        token.append(CHARACTERS.charAt(randomindex));
        
    }
    return token.toString();
}
    //code randiom
    private void EnterDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterDataBtnActionPerformed
        SQLConection sqlConnection = new SQLConection();
        Connection conn = sqlConnection.StartSQLConnection();
        
        if(NameFieldCreateUser.getText().isEmpty() || UserNumberTargetField.getText().isEmpty() || PINfieldUser.getText().isEmpty()
            || BalanceUserField.getText().isEmpty() || MaxAmountUserFIeld.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Tienes que rellenar todos los campos jajaj","Cuando ella gambetea entre la tempestad",JOptionPane.INFORMATION_MESSAGE);
            return;
        }      
        BigDecimal balance; 
        BigDecimal maxAmount;
        
        try{
            balance = new BigDecimal(BalanceUserField.getText());
            maxAmount = new BigDecimal(MaxAmountUserFIeld.getText());

        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "No se pueden agregar caracteres ni cadenas de texto al saldo ni al monto maximo ni al pin ni tarjeta"
                    + " unicamente caracteres numericos.","te encargo porfa",JOptionPane.WARNING_MESSAGE);
            return;
        }       
        
        String name = NameFieldCreateUser.getText();
        String targetNumber = UserNumberTargetField.getText();
        String PIN = PINfieldUser.getText();
        
        if(targetNumber.length() != 16){
            JOptionPane.showMessageDialog(this, "Recordate que los numeros de tarjeta solo puede tener 16 caracteres.","hola",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(PIN.length() != 4){
            JOptionPane.showMessageDialog(this, "Recordate que los numeros del PIN solo puede tener 4 caracteres.","sexo",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
                
        String token = generateUniqueToken(); 
        
        String sql = "INSERT INTO CREAR_USUARIOS (nombre, numero_tarjeta,PIN,saldo,monto_maximo,token,TokenTipo) VALUES (?,?,?,?,?,?,0)";
        try(PreparedStatement psmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)){
            psmt.setString(1, name);
            psmt.setString(2, targetNumber);
            psmt.setString(3, PIN);
            psmt.setBigDecimal(4, balance);
            psmt.setBigDecimal(5, maxAmount);
            psmt.setString(6, token);
            
            
            
            int rowsAffected = psmt.executeUpdate();
            if(rowsAffected > 0){
                ResultSet generatedKeys = psmt.getGeneratedKeys();
                if (generatedKeys.next()) {
                int idUsuario = generatedKeys.getInt(1);
                
                String sqlInsert = "INSERT INTO CONSULTA_USUARIO (id_usuario, monto_maximo_disponible, monto_retirado_hasta_ahora, saldo_actual, ultimo_acceso) VALUES (?, ?, 0, ?, NULL);";
                try (PreparedStatement pstmt = conn.prepareStatement(sqlInsert)) {
                BigDecimal MaxRestAmoun = maxAmount;
                if(maxAmount.compareTo(balance) > 0){
                    MaxRestAmoun = balance;
                }
                else if(maxAmount.compareTo(balance) < 0){
                    MaxRestAmoun = maxAmount;
                }
                pstmt.setInt(1, idUsuario);           
                pstmt.setBigDecimal(2, MaxRestAmoun);    
                pstmt.setBigDecimal(3, balance);      

                int rowsAffectedConsulta = pstmt.executeUpdate();
                if (rowsAffectedConsulta > 0) {
                    JOptionPane.showMessageDialog(this, "Usuario agregado correctamente");
                } else {
                    JOptionPane.showMessageDialog(this, "Error al registrar la consulta");
                        }
                    }           
                }
                
            }
            else{
                JOptionPane.showMessageDialog(this, "Error al agregar el usuario");
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error al conectar la base de datos" + e.getMessage(),"jajaj",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_EnterDataBtnActionPerformed

    private void PINfieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PINfieldUserActionPerformed
    

    }//GEN-LAST:event_PINfieldUserActionPerformed

    private void PINfieldUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PINfieldUserKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) { 
            evt.consume();
        }
    }//GEN-LAST:event_PINfieldUserKeyTyped

    private void PINfieldUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PINfieldUserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PINfieldUserKeyPressed

    private void PINfieldUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PINfieldUserKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_PINfieldUserKeyReleased

    private void UserNumberTargetFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserNumberTargetFieldKeyTyped
       char c = evt.getKeyChar();
       if(!Character.isDigit(c)){
           evt.consume();
       }
    }//GEN-LAST:event_UserNumberTargetFieldKeyTyped

    private void BalanceUserFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BalanceUserFieldKeyTyped
       char c = evt.getKeyChar();
       if(!Character.isDigit(c)){
           evt.consume();
       }
    }//GEN-LAST:event_BalanceUserFieldKeyTyped

    private void MaxAmountUserFIeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaxAmountUserFIeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaxAmountUserFIeldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserCreation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackLobby;
    private javax.swing.JTextField BalanceUserField;
    private javax.swing.JPanel CenterBg;
    private javax.swing.JButton EnterDataBtn;
    private javax.swing.JTextField MaxAmountUserFIeld;
    private javax.swing.JTextField NameFieldCreateUser;
    private javax.swing.JTextField PINfieldUser;
    private javax.swing.JPanel Upperbg;
    private javax.swing.JTextField UserNumberTargetField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
