/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserJframes;

import AdminJframes.TokenOptionCreationUser;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import whatever.proyectocajero.SQLConection;
import whatever.proyectocajero.SharedUserDATA;

/**
 *
 * @author ALEJANDRO REQUENA
 */
public class MainUserLobby extends javax.swing.JFrame {

    /**
     * Creates new form MainUserLobby
     */
    public MainUserLobby() {
        initComponents();
        this.setLocationRelativeTo(null);
        NameLabel.setText(SharedUserDATA.getUserLoginName());
        
        SQLConection sqlConnection = new SQLConection();
        Connection conn = sqlConnection.StartSQLConnection();
        actualizarUltimoAcceso(conn);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        DepositMoveBtn = new javax.swing.JButton();
        PinChangeMoveBtn = new javax.swing.JButton();
        BalanceUserMoveBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        LatestTransactionsMoveBtn = new javax.swing.JButton();
        retreatsMoveBtn = new javax.swing.JButton();
        ComeBackBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(59, 63, 70));

        DepositMoveBtn.setBackground(new java.awt.Color(173, 173, 173));
        DepositMoveBtn.setBorder(null);
        DepositMoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositMoveBtnActionPerformed(evt);
            }
        });

        PinChangeMoveBtn.setBackground(new java.awt.Color(173, 173, 173));
        PinChangeMoveBtn.setBorder(null);
        PinChangeMoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinChangeMoveBtnActionPerformed(evt);
            }
        });

        BalanceUserMoveBtn.setBackground(new java.awt.Color(173, 173, 173));
        BalanceUserMoveBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), null));
        BalanceUserMoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceUserMoveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PinChangeMoveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepositMoveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalanceUserMoveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(BalanceUserMoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DepositMoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PinChangeMoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(59, 63, 70));

        LatestTransactionsMoveBtn.setBackground(new java.awt.Color(173, 173, 173));
        LatestTransactionsMoveBtn.setBorder(null);
        LatestTransactionsMoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatestTransactionsMoveBtnActionPerformed(evt);
            }
        });

        retreatsMoveBtn.setBackground(new java.awt.Color(173, 173, 173));
        retreatsMoveBtn.setBorder(null);
        retreatsMoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retreatsMoveBtnActionPerformed(evt);
            }
        });

        ComeBackBtn.setBackground(new java.awt.Color(173, 173, 173));
        ComeBackBtn.setBorder(null);
        ComeBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComeBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LatestTransactionsMoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retreatsMoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComeBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(ComeBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LatestTransactionsMoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(retreatsMoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setBackground(new java.awt.Color(59, 63, 70));
        jPanel4.setPreferredSize(new java.awt.Dimension(920, 70));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bienvenido Usuario: ");
        jPanel4.add(jLabel10, new java.awt.GridBagConstraints());

        NameLabel.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("jLabel1");
        jPanel4.add(NameLabel, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(59, 63, 70));
        jPanel5.setPreferredSize(new java.awt.Dimension(920, 70));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1007, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBackground(new java.awt.Color(60, 70, 92));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cambio de PIN");
        jPanel7.add(jLabel2, new java.awt.GridBagConstraints());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Retiros");
        jPanel8.add(jLabel3, new java.awt.GridBagConstraints());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Depósito");
        jPanel9.add(jLabel4, new java.awt.GridBagConstraints());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ver últimas transacciones");
        jPanel10.add(jLabel5, new java.awt.GridBagConstraints());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Ver Saldo");
        jPanel11.add(jLabel6, new java.awt.GridBagConstraints());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Volver al inicio");
        jPanel12.add(jLabel7, new java.awt.GridBagConstraints());

        jPanel14.setBackground(new java.awt.Color(60, 70, 92));
        jPanel14.setLayout(new java.awt.GridBagLayout());

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 70)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ATP");
        jPanel14.add(jLabel9, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComeBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComeBackBtnActionPerformed
        LoginUser loginUserWindow = new LoginUser();
        loginUserWindow.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_ComeBackBtnActionPerformed
   
    private void PinChangeMoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinChangeMoveBtnActionPerformed
        if(SharedUserDATA.getTokenTipo() == 0){
            ModifyPIN ModifPIN = new ModifyPIN();
            ModifPIN.setVisible(true);
            this.dispose();
        }
        else if(SharedUserDATA.getTokenTipo() == 1){
            ModifyPINStatic ModifyPINStatic = new ModifyPINStatic();
            ModifyPINStatic.setVisible(true);
            this.dispose();
        }

        
    }//GEN-LAST:event_PinChangeMoveBtnActionPerformed

    private void retreatsMoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retreatsMoveBtnActionPerformed
        if(SharedUserDATA.getTokenTipo() == 0){
            retreatsUser retreatsWindow = new retreatsUser();
            retreatsWindow.setVisible(true);
            this.dispose();
        }
        else if(SharedUserDATA.getTokenTipo() == 1){
            retreatsUserStatic retreatsWindowStatic = new retreatsUserStatic();
            retreatsWindowStatic.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_retreatsMoveBtnActionPerformed

    private void DepositMoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositMoveBtnActionPerformed
        if(SharedUserDATA.getTokenTipo() == 0){
            DepositUser DepositWindow = new DepositUser();
            DepositWindow.setVisible(true);
            this.dispose();
        }
        else if(SharedUserDATA.getTokenTipo() == 1){
            DepositUserSTATIC DepositWindowStatic = new DepositUserSTATIC();
            DepositWindowStatic.setVisible(true);
            this.dispose();
        }
       
    }//GEN-LAST:event_DepositMoveBtnActionPerformed

    private void LatestTransactionsMoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatestTransactionsMoveBtnActionPerformed
    TransactionsUser transactionWindow = new TransactionsUser();
    transactionWindow.setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_LatestTransactionsMoveBtnActionPerformed

    private void BalanceUserMoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceUserMoveBtnActionPerformed
       BalanceUser balanceWindow = new BalanceUser();
       balanceWindow.setVisible(true);
        
       this.dispose();
    }//GEN-LAST:event_BalanceUserMoveBtnActionPerformed
    
    private void actualizarUltimoAcceso(Connection conn) {
    String UpdateConsulta = "UPDATE CONSULTA_USUARIO SET saldo_actual = ?, monto_retirado_hasta_ahora = ?, monto_maximo_disponible = ? WHERE id_usuario = ?";
    try (PreparedStatement UpdateStmt = conn.prepareStatement(UpdateConsulta)) {

        System.out.println("Saldo: " + SharedUserDATA.getSaldoUser());
        System.out.println("Monto Retirado Hoy: " + SharedUserDATA.getMontoRetiradoHoy());
        BigDecimal montoAvaible = SharedUserDATA.getMontoMax().subtract(SharedUserDATA.getMontoRetiradoHoy());
        System.out.println("Monto Maximo Disponible: " + montoAvaible);
        System.out.println("ID Usuario: " + SharedUserDATA.getId_usuario());
        
        UpdateStmt.setBigDecimal(1, SharedUserDATA.getSaldoUser());
        UpdateStmt.setBigDecimal(2, SharedUserDATA.getMontoRetiradoHoy());
        UpdateStmt.setBigDecimal(3, montoAvaible); 
        UpdateStmt.setInt(4, SharedUserDATA.getId_usuario());

        int rowsAffected = UpdateStmt.executeUpdate();
        System.out.println("Rows affected: " + rowsAffected);
        if (rowsAffected == 0) {
            System.out.println("No rows updated. Check if id_usuario exists.");
        }

        
        conn.commit();  
    } catch (SQLException e) {
        e.printStackTrace();  
        JOptionPane.showMessageDialog(this, "Error al actualizar el último acceso: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUserLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUserLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUserLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUserLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUserLobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BalanceUserMoveBtn;
    private javax.swing.JButton ComeBackBtn;
    private javax.swing.JButton DepositMoveBtn;
    private javax.swing.JButton LatestTransactionsMoveBtn;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JButton PinChangeMoveBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton retreatsMoveBtn;
    // End of variables declaration//GEN-END:variables
}
