/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserJframes;

import java.math.BigDecimal;
import java.security.SecureRandom;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.JOptionPane;
import whatever.proyectocajero.MoneyManager;
import whatever.proyectocajero.SQLConection;
import whatever.proyectocajero.SharedUserDATA;

/**
 *
 * @author ALEJANDRO REQUENA
 */
public class RetreatsMoneyUser extends javax.swing.JFrame {
MoneyManager MoneyMan = new MoneyManager();
    /**
     * Creates new form RetreatsMoneyUser
     */
    public RetreatsMoneyUser() {
        initComponents();
        this.setLocationRelativeTo(null);
        CantidaTotalDisplay.setText(MoneyMan.getTotalMoney().toString());    
        LabelDen1.setText(String.valueOf(MoneyMan.getMoney_1()));
        LabelDen5.setText(String.valueOf(MoneyMan.getMoney_5()));
        LabelDen10.setText(String.valueOf(MoneyMan.getMoney_10()));
        LabelDen20.setText(String.valueOf(MoneyMan.getMoney_20()));
        LabelDen50.setText(String.valueOf(MoneyMan.getMoney_50()));
        LabelDen100.setText(String.valueOf(MoneyMan.getMoney_100()));
        LabelDen200.setText(String.valueOf(MoneyMan.getMoney_200()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Add5Field = new javax.swing.JButton();
        Add1Field = new javax.swing.JButton();
        Add10Field = new javax.swing.JButton();
        Add20Field = new javax.swing.JButton();
        BackHomeLobby = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Add50Field = new javax.swing.JButton();
        RetireBtn = new javax.swing.JButton();
        Add200Field = new javax.swing.JButton();
        Add100Field = new javax.swing.JButton();
        CancelAllBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LabelDen1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        LabelDen5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LabelDen50 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        LabelDen200 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        LabelDen100 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CantidaTotalDisplay = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        LabelDen10 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        LabelDen20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(59, 63, 70));

        Add5Field.setBackground(new java.awt.Color(173, 173, 173));
        Add5Field.setBorder(null);
        Add5Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add5FieldActionPerformed(evt);
            }
        });

        Add1Field.setBackground(new java.awt.Color(173, 173, 173));
        Add1Field.setBorder(null);
        Add1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1FieldActionPerformed(evt);
            }
        });

        Add10Field.setBackground(new java.awt.Color(173, 173, 173));
        Add10Field.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), null));
        Add10Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add10FieldActionPerformed(evt);
            }
        });

        Add20Field.setBackground(new java.awt.Color(173, 173, 173));
        Add20Field.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), null));
        Add20Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add20FieldActionPerformed(evt);
            }
        });

        BackHomeLobby.setBackground(new java.awt.Color(255, 255, 255));
        BackHomeLobby.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        BackHomeLobby.setForeground(new java.awt.Color(0, 0, 0));
        BackHomeLobby.setText("Regresar");
        BackHomeLobby.setBorder(null);
        BackHomeLobby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackHomeLobbyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BackHomeLobby, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Add1Field, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(Add5Field, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(Add10Field, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(Add20Field, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(BackHomeLobby, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(Add20Field, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Add10Field, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Add5Field, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Add1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(59, 63, 70));

        Add50Field.setBackground(new java.awt.Color(173, 173, 173));
        Add50Field.setBorder(null);
        Add50Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add50FieldActionPerformed(evt);
            }
        });

        RetireBtn.setBackground(new java.awt.Color(173, 173, 173));
        RetireBtn.setBorder(null);
        RetireBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetireBtnActionPerformed(evt);
            }
        });

        Add200Field.setBackground(new java.awt.Color(173, 173, 173));
        Add200Field.setBorder(null);
        Add200Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add200FieldActionPerformed(evt);
            }
        });

        Add100Field.setBackground(new java.awt.Color(173, 173, 173));
        Add100Field.setBorder(null);
        Add100Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add100FieldActionPerformed(evt);
            }
        });

        CancelAllBtn.setBackground(new java.awt.Color(255, 0, 102));
        CancelAllBtn.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        CancelAllBtn.setForeground(new java.awt.Color(255, 255, 255));
        CancelAllBtn.setText("Cancelar");
        CancelAllBtn.setBorder(null);
        CancelAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelAllBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add50Field, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RetireBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add200Field, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add100Field, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(CancelAllBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CancelAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(Add200Field, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Add100Field, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Add50Field, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RetireBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setBackground(new java.awt.Color(59, 63, 70));
        jPanel4.setPreferredSize(new java.awt.Dimension(920, 70));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Escoja las denominaciones a retirar ");
        jPanel4.add(jLabel10, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(59, 63, 70));
        jPanel5.setPreferredSize(new java.awt.Dimension(920, 70));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1007, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBackground(new java.awt.Color(60, 70, 92));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("1.00Q ");
        jPanel7.add(jLabel2, new java.awt.GridBagConstraints());

        LabelDen1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        LabelDen1.setForeground(new java.awt.Color(0, 0, 0));
        LabelDen1.setText("jLabel11");
        jPanel7.add(LabelDen1, new java.awt.GridBagConstraints());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Retirar la cantidad");
        jPanel8.add(jLabel3, new java.awt.GridBagConstraints());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("5.00Q ");
        jPanel9.add(jLabel4, new java.awt.GridBagConstraints());

        LabelDen5.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        LabelDen5.setForeground(new java.awt.Color(0, 0, 0));
        LabelDen5.setText("jLabel11");
        jPanel9.add(LabelDen5, new java.awt.GridBagConstraints());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("50.00Q ");
        jPanel10.add(jLabel5, new java.awt.GridBagConstraints());

        LabelDen50.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        LabelDen50.setForeground(new java.awt.Color(0, 0, 0));
        LabelDen50.setText("jLabel11");
        jPanel10.add(LabelDen50, new java.awt.GridBagConstraints());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("200.00Q ");
        jPanel11.add(jLabel6, new java.awt.GridBagConstraints());

        LabelDen200.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        LabelDen200.setForeground(new java.awt.Color(0, 0, 0));
        LabelDen200.setText("jLabel11");
        jPanel11.add(LabelDen200, new java.awt.GridBagConstraints());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("100.00Q ");
        jPanel12.add(jLabel7, new java.awt.GridBagConstraints());

        LabelDen100.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        LabelDen100.setForeground(new java.awt.Color(0, 0, 0));
        LabelDen100.setText("jLabel11");
        jPanel12.add(LabelDen100, new java.awt.GridBagConstraints());

        jPanel14.setBackground(new java.awt.Color(60, 70, 92));
        jPanel14.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cantidad total: ");
        jPanel14.add(jLabel1, new java.awt.GridBagConstraints());

        CantidaTotalDisplay.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        CantidaTotalDisplay.setForeground(new java.awt.Color(255, 255, 255));
        CantidaTotalDisplay.setText("x");
        jPanel14.add(CantidaTotalDisplay, new java.awt.GridBagConstraints());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("10.00Q ");
        jPanel13.add(jLabel8, new java.awt.GridBagConstraints());

        LabelDen10.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        LabelDen10.setForeground(new java.awt.Color(0, 0, 0));
        LabelDen10.setText("jLabel11");
        jPanel13.add(LabelDen10, new java.awt.GridBagConstraints());

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new java.awt.GridBagLayout());

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("20.00Q ");
        jPanel15.add(jLabel9, new java.awt.GridBagConstraints());

        LabelDen20.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        LabelDen20.setForeground(new java.awt.Color(0, 0, 0));
        LabelDen20.setText("jLabel11");
        jPanel15.add(LabelDen20, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add5FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add5FieldActionPerformed
        MoneyMan.setMoney_5( MoneyMan.getMoney_5() + 1);
        MoneyMan.setTotalMoney(MoneyMan.getTotalMoney().add(BigDecimal.valueOf(5.00)));
        LabelDen5.setText(String.valueOf("( +" + MoneyMan.getMoney_5() + " )"));
        CantidaTotalDisplay.setText(MoneyMan.getTotalMoney().toString());

    }//GEN-LAST:event_Add5FieldActionPerformed

    private void Add1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1FieldActionPerformed
        //check every int changes int 1, bcz idk how can i get that, serotas
        MoneyMan.setMoney_1( MoneyMan.getMoney_1() + 1);
        MoneyMan.setTotalMoney(MoneyMan.getTotalMoney().add(BigDecimal.valueOf(1.00)));
        LabelDen1.setText(String.valueOf("( +" + MoneyMan.getMoney_1() + " )"));
        CantidaTotalDisplay.setText(MoneyMan.getTotalMoney().toString());

    }//GEN-LAST:event_Add1FieldActionPerformed

    private void Add10FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add10FieldActionPerformed
        MoneyMan.setMoney_10(MoneyMan.getMoney_10() + 1);
        MoneyMan.setTotalMoney(MoneyMan.getTotalMoney().add(BigDecimal.valueOf(10.00)));
        LabelDen10.setText(String.valueOf("( +" + MoneyMan.getMoney_10() + " )"));
        CantidaTotalDisplay.setText(MoneyMan.getTotalMoney().toString());
        
    }//GEN-LAST:event_Add10FieldActionPerformed

    private void Add50FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add50FieldActionPerformed
       MoneyMan.setMoney_50(MoneyMan.getMoney_50() + 1);
       MoneyMan.setTotalMoney(MoneyMan.getTotalMoney().add(BigDecimal.valueOf(50.00)));
       LabelDen50.setText(String.valueOf("( +" + MoneyMan.getMoney_50() + " )"));
       CantidaTotalDisplay.setText(MoneyMan.getTotalMoney().toString());
    }//GEN-LAST:event_Add50FieldActionPerformed
    private String generateUniqueToken() { //method random
        Random random = new SecureRandom();
        final String CHARACTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        int tokenLength = 10;
        StringBuilder token = new StringBuilder(tokenLength);
        for (int i = 0; i < tokenLength; i++) {
            int randomindex = random.nextInt(CHARACTERS.length());
            token.append(CHARACTERS.charAt(randomindex));

        }
        return token.toString();
    }
    private void RetireBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetireBtnActionPerformed
        SQLConection sqlConnection = new SQLConection();
        Connection conn = sqlConnection.StartSQLConnection();
        
        if(!(MoneyMan.getTotalMoney().compareTo(BigDecimal.ZERO) == 0)){
            int idCajero = GetId();
            
        try {
            if(idCajero == -1) {
                JOptionPane.showMessageDialog(this, "No hay registro de ningun cajero");
                return;
            }
            else if(!isCajeroInitialized(conn, idCajero)){
                JOptionPane.showMessageDialog(this, "El cajero NO ha sido inicializado.");
                return;
            }
            System.out.println(SharedUserDATA.getSaldoUser());
            String tokenTransaccion = generateUniqueToken();
            if(SharedUserDATA.getSaldoUser().compareTo(BigDecimal.ZERO) == 0){
            JOptionPane.showMessageDialog(this, "Ya no tienes saldo");
            return;
            }
            if (SharedUserDATA.getSaldoUser().compareTo(MoneyMan.getTotalMoney()) >= 0) {
                String sqlCheck = "SELECT total_dinero, billetes_200, billetes_100, billetes_50, billetes_20, billetes_10, billetes_5, billetes_1 FROM CAJERO WHERE id_cajero = ?";
                try (PreparedStatement checkSQL = conn.prepareStatement(sqlCheck)) {
                    checkSQL.setInt(1, idCajero);
                    try (ResultSet rs = checkSQL.executeQuery()) {
                        if (rs.next()) {
                            int currentBilletes1 = rs.getInt("billetes_1");
                            int currentBilletes5 = rs.getInt("billetes_5");
                            int currentBilletes10 = rs.getInt("billetes_10");
                            int currentBilletes20 = rs.getInt("billetes_20");
                            int currentBilletes50 = rs.getInt("billetes_50");
                            int currentBilletes100 = rs.getInt("billetes_100");
                            int currentBilletes200 = rs.getInt("billetes_200");
                            BigDecimal currentTotalDinero = rs.getBigDecimal("total_dinero");

                            if (MoneyMan.getMoney_1() > currentBilletes1 || MoneyMan.getMoney_5() > currentBilletes5
                                    || MoneyMan.getMoney_10() > currentBilletes10 || MoneyMan.getMoney_20() > currentBilletes20
                                    || MoneyMan.getMoney_50() > currentBilletes50 || MoneyMan.getMoney_100() > currentBilletes100
                                    || MoneyMan.getMoney_200() > currentBilletes200) {
                                JOptionPane.showMessageDialog(this, "El cajero no tiene las denominaciones suficientes para este retiro.");
                                return;
                            }
                            
                            if(currentTotalDinero.compareTo(MoneyMan.getTotalMoney()) == -1){
                                System.out.println("1");
                                JOptionPane.showMessageDialog(this, "Dinero total insuficiente en el cajero.");
                                return;
                            }
                                 
                            if (MoneyMan.getTotalMoney().compareTo(currentTotalDinero) > 0) {
                                System.out.println("2");
                                JOptionPane.showMessageDialog(this, "Dinero total insuficiente en el cajero.");
                                return;
                            }
                            BigDecimal x = SharedUserDATA.getMontoRetiradoHoy();
                            BigDecimal test = x.add(MoneyMan.getTotalMoney());

                            if (SharedUserDATA.getMontoMax().compareTo(test) < 0) {
                                JOptionPane.showMessageDialog(this, "Haz alcanzado el maximo para retirar hoy");
                                return;
                                }   
                            
                            
                            if(MoneyMan.getTotalMoney().compareTo(SharedUserDATA.getSaldoUser()) == 1){
                                JOptionPane.showMessageDialog(this, "No tienes suficiente saldo para hacer esto","Muere JORGE CIFUENTES",JOptionPane.WARNING_MESSAGE);
                                return;
                            }
                            
                            int updatedBilletes1 = currentBilletes1 - MoneyMan.getMoney_1();
                            int updatedBilletes5 = currentBilletes5 - MoneyMan.getMoney_5();
                            int updatedBilletes10 = currentBilletes10 - MoneyMan.getMoney_10();
                            int updatedBilletes20 = currentBilletes20 - MoneyMan.getMoney_20();
                            int updatedBilletes50 = currentBilletes50 - MoneyMan.getMoney_50();
                            int updatedBilletes100 = currentBilletes100 - MoneyMan.getMoney_100();
                            int updatedBilletes200 = currentBilletes200 - MoneyMan.getMoney_200();

                            BigDecimal newTotalDinero = new BigDecimal(updatedBilletes1 * 1 + updatedBilletes5 * 5 + updatedBilletes10 * 10
                                    + updatedBilletes20 * 20 + updatedBilletes50 * 50 + updatedBilletes100 * 100
                                    + updatedBilletes200 * 200);

                            String updateSQL = "UPDATE CAJERO SET total_dinero = ?, billetes_200 = ?, billetes_100 = ?, billetes_50 = ?, billetes_20 = ?, billetes_10 = ?, billetes_5 = ?, billetes_1 = ? WHERE id_cajero = ?";
                            try (PreparedStatement updateStmt = conn.prepareStatement(updateSQL)) {
                                updateStmt.setBigDecimal(1, newTotalDinero);
                                updateStmt.setInt(2, updatedBilletes200);
                                updateStmt.setInt(3, updatedBilletes100);
                                updateStmt.setInt(4, updatedBilletes50);
                                updateStmt.setInt(5, updatedBilletes20);
                                updateStmt.setInt(6, updatedBilletes10);
                                updateStmt.setInt(7, updatedBilletes5);
                                updateStmt.setInt(8, updatedBilletes1);
                                updateStmt.setInt(9, idCajero);
                                
                                int rowsAffected = updateStmt.executeUpdate();
                                if (rowsAffected > 0) {
                                    BigDecimal newSaldo = SharedUserDATA.getSaldoUser().subtract(MoneyMan.getTotalMoney());
                                    String updateUserSQL = "UPDATE CREAR_USUARIOS SET saldo = ?,monto_retirado_hoy = ? WHERE id_usuario = ?";
                                    try (PreparedStatement updateUserStmt = conn.prepareStatement(updateUserSQL)) {
                                        SharedUserDATA.setMontoRetiradoHoy(SharedUserDATA.getMontoRetiradoHoy().add(MoneyMan.getTotalMoney()));
                                        updateUserStmt.setBigDecimal(1, newSaldo);
                                        updateUserStmt.setBigDecimal(2, SharedUserDATA.getMontoRetiradoHoy());
                                        updateUserStmt.setInt(3, SharedUserDATA.getId_usuario());
                                        SharedUserDATA.setSaldoUser(newSaldo);
                                        int updateUserResult = updateUserStmt.executeUpdate();
                                        if (updateUserResult > 0) {
                                            
                                            String insertTransactionSQL = "INSERT INTO TRANSACCIONES (id_usuario, id_cajero, tipo_transaccion, monto, token, tokenTransaccion) VALUES (?, ?, 'Retiro', ?, ?, ?)";
                                            try (PreparedStatement insertTransactionStmt = conn.prepareStatement(insertTransactionSQL)) {
                                                insertTransactionStmt.setInt(1, SharedUserDATA.getId_usuario());
                                                insertTransactionStmt.setInt(2, idCajero);
                                                insertTransactionStmt.setBigDecimal(3, MoneyMan.getTotalMoney());
                                                insertTransactionStmt.setString(4, SharedUserDATA.getToken());
                                                insertTransactionStmt.setString(5, tokenTransaccion);

                                                int transactionResult = insertTransactionStmt.executeUpdate();
                                                if (transactionResult > 0) {
                                                    
                                                    JOptionPane.showMessageDialog(this, "Retiro exitoso. El saldo ha sido actualizado.");
                                                } else {
                                                    JOptionPane.showMessageDialog(this, "Error al registrar la transacción.");
                                                }
                                            }
                                        } else {
                                            JOptionPane.showMessageDialog(this, "Error al actualizar el saldo del usuario.");
                                        }
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(this, "Error al actualizar los datos del cajero.");
                                }
                            }
                        }
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "No tienes suficiente saldo para hacer esto","Muere JORGE CIFUENTES",JOptionPane.WARNING_MESSAGE);
                                return;
            }

            } catch(SQLException e){
                JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage());
            }
          
        }
        else{
            JOptionPane.showMessageDialog(this, "De nada nos servira depostar 0.00Q","TE CUESTA VAA?",JOptionPane.WARNING_MESSAGE);
            } 
        

    }//GEN-LAST:event_RetireBtnActionPerformed
    public int GetId(){
        SQLConection sqlConnection = new SQLConection();
        Connection conn = sqlConnection.StartSQLConnection();
        int idCajero = -1;
        String sqlId = "SELECT TOP 1 id_cajero FROM CAJERO ORDER BY id_cajero DESC";
        try(PreparedStatement psmt = conn.prepareStatement(sqlId)){
            ResultSet rs = psmt.executeQuery();
            if(rs.next()){
               return idCajero = rs.getInt("id_cajero");
            }
        } catch(SQLException e){
            return -1;
        }  
        return idCajero;
    }
    private void Add200FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add200FieldActionPerformed
        MoneyMan.setMoney_200(MoneyMan.getMoney_200() + 1);
        MoneyMan.setTotalMoney(MoneyMan.getTotalMoney().add(BigDecimal.valueOf(200.00)));
        LabelDen200.setText(String.valueOf("( +" + MoneyMan.getMoney_200() + " )"));
        CantidaTotalDisplay.setText(MoneyMan.getTotalMoney().toString());
    }//GEN-LAST:event_Add200FieldActionPerformed

    private void Add20FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add20FieldActionPerformed
        MoneyMan.setMoney_20(MoneyMan.getMoney_20() + 1);
        MoneyMan.setTotalMoney(MoneyMan.getTotalMoney().add(BigDecimal.valueOf(20.00)));
        LabelDen20.setText(String.valueOf("( +" + MoneyMan.getMoney_20() + " )"));
        CantidaTotalDisplay.setText(MoneyMan.getTotalMoney().toString());
    }//GEN-LAST:event_Add20FieldActionPerformed

    private void Add100FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add100FieldActionPerformed
        MoneyMan.setMoney_100(MoneyMan.getMoney_100() + 1);
        MoneyMan.setTotalMoney(MoneyMan.getTotalMoney().add(BigDecimal.valueOf(100.00)));
        LabelDen100.setText(String.valueOf("( +" + MoneyMan.getMoney_100() + " )"));
        CantidaTotalDisplay.setText(MoneyMan.getTotalMoney().toString());
    }//GEN-LAST:event_Add100FieldActionPerformed

    private void BackHomeLobbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackHomeLobbyActionPerformed
        MainUserLobby Userwindow = new MainUserLobby();
        Userwindow.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_BackHomeLobbyActionPerformed

    private void CancelAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelAllBtnActionPerformed
        MoneyMan.setMoney_1(0);
        MoneyMan.setMoney_5(0);
        MoneyMan.setMoney_10(0);
        MoneyMan.setMoney_20(0);
        MoneyMan.setMoney_50(0);
        MoneyMan.setMoney_100(0);
        MoneyMan.setMoney_200(0);
        // idk how to change the decimal value jajahajaja 
        MoneyMan.setTotalMoney(BigDecimal.valueOf(0.00));

        LabelDen1.setText(String.valueOf("( " + MoneyMan.getMoney_1() + " )"));
        LabelDen5.setText(String.valueOf("( " + MoneyMan.getMoney_5() + " )"));
        LabelDen10.setText(String.valueOf("( " + MoneyMan.getMoney_10() + " )"));
        LabelDen20.setText(String.valueOf("( " + MoneyMan.getMoney_20() + " )"));
        LabelDen50.setText(String.valueOf("( " + MoneyMan.getMoney_50() + " )"));
        LabelDen100.setText(String.valueOf("( " + MoneyMan.getMoney_100() + " )"));
        LabelDen200.setText(String.valueOf("( " + MoneyMan.getMoney_200() + " )"));
        CantidaTotalDisplay.setText(MoneyMan.getTotalMoney().toString());
    }//GEN-LAST:event_CancelAllBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetreatsMoneyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetreatsMoneyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetreatsMoneyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetreatsMoneyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RetreatsMoneyUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add100Field;
    private javax.swing.JButton Add10Field;
    private javax.swing.JButton Add1Field;
    private javax.swing.JButton Add200Field;
    private javax.swing.JButton Add20Field;
    private javax.swing.JButton Add50Field;
    private javax.swing.JButton Add5Field;
    private javax.swing.JButton BackHomeLobby;
    private javax.swing.JButton CancelAllBtn;
    private javax.swing.JLabel CantidaTotalDisplay;
    private javax.swing.JLabel LabelDen1;
    private javax.swing.JLabel LabelDen10;
    private javax.swing.JLabel LabelDen100;
    private javax.swing.JLabel LabelDen20;
    private javax.swing.JLabel LabelDen200;
    private javax.swing.JLabel LabelDen5;
    private javax.swing.JLabel LabelDen50;
    private javax.swing.JButton RetireBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables

    private boolean isCajeroInitialized(Connection conn, int idCajero) throws SQLException {
        String query = "SELECT estado_inicializado FROM CAJERO WHERE id_cajero = ?";  // Consulta SQL
        try (PreparedStatement psmt = conn.prepareStatement(query)) {
            psmt.setInt(1, idCajero);  // Establece el ID del cajero

            try (ResultSet rs = psmt.executeQuery()) {
                if (rs.next()) {
                    // Obtener el valor del campo estado_inicializado
                    boolean estadoInicializado = rs.getBoolean("estado_inicializado");
                    return estadoInicializado;  // Devuelve true si está inicializado (1), false si no (0)
                }
            }
        }
        return false;  // Si no se encuentra el cajero o no hay resultados
    }
}
